### ISSUE TITLE
I'm curious if there is a way to create subforums with this module?

### ISSUE THREAD

**Issue by Chromebuster** [Jetski5822/NGM.Forum#8]
Hello all,
I'm currently setting up my forums on our site, and I at the moment cannot find a way to layer forums underneath forums. (a.k.a. subforums)  Is this an upcoming feature in the next version of this module?  If I were a coder, I'd make it possible, but since I'm not, I'm asking here.  Thanks all.

**Comment by Jetski5822** [comment]
Hey hsimah - what exactly are you trying to do? What do you mean configure sub forums? different to the parent yes?

**Comment by hsimah** [comment]
Hi Nicholas,


I'm a Windows Forms rev by trade, but I am trying to make the jump to web stuff. I'm building a website for my cycling club. I decided Orchard looked good. The trouble is there is a lot of config and a lack of documentation (or at least I can’t find it!). I am making progress, though. You forum module looks perfect for what we need.


What I am trying to do is make a forum structure like this:


Category 1 (e.g. Road Cycling)


Forum 1 (e.g. Training)

Forum 2 (e.g. Racing)

Category 2 (e.g. Mountain Biking)


Forum 1

Forum 2

Category 3


Forum 1

Forum 2

Forum 3


I ended up creating the forums and adding a field to the content definition to store the category. I then created three queries to retrieve forums with the set category. I then created a new layer with some content parts containing my three queries. It works, but it seems like a really roundabout way to accomplish what I want.


I also used a list to do this, but the Orchard site says lists are now deprecated, so I didn't keep that solution.


Sorry for being a nuisance. I really like this Orchard software and want to get stuck into it. I read some of your blog posts about contributing to open source software and it struck a chord - it sounds like something I would like to get involved in, too.


Cheers,


Hamish





Sent from Surface Pro





From: Nicholas Mayne
Sent: ‎Saturday‎, ‎3‎ ‎January‎ ‎2015 ‎11‎:‎03‎ ‎PM
To: Jetski5822/NGM.Forum
Cc: Hamish Blake





Hey hsimah - what exactly are you trying to do? What do you mean configure sub forums? different to the parent yes?
